#!/usr/bin/env python3
"""
Convert .config (key=value) to a C header.
Strips the CONFIG_ prefix so existing source macros match.
Usage: python3 tools/config_to_header.py .config build/include/cli_kconfig.h
"""
import re
import sys
import os


def convert(dotconfig_path: str, header_path: str):
    if not os.path.exists(dotconfig_path):
        print(f"Error: {dotconfig_path} not found.")
        sys.exit(1)

    lines = []
    with open(dotconfig_path, "r", encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            # 格式: # CONFIG_XXX is not set
            if line.startswith("#") and "is not set" in line:
                m = re.match(r"#\s*CONFIG_(\w+)\s+is not set", line)
                if m:
                    lines.append(f"/* #undef {m.group(1)} */")
                continue

            # 格式: CONFIG_XXX=value
            m = re.match(r"CONFIG_(\w+)=(.+)", line)
            if not m:
                continue
            name, val = m.group(1), m.group(2)

            if val == "y":
                lines.append(f"#define {name} 1")
            elif val == "n":
                lines.append(f"/* #undef {name} */")
            else:
                # int, hex, string
                lines.append(f"#define {name} {val}")

    os.makedirs(os.path.dirname(header_path), exist_ok=True)

    with open(header_path, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by config_to_header.py, DO NOT EDIT */\n")
        f.write("#ifndef _CLI_KCONFIG_H_\n")
        f.write("#define _CLI_KCONFIG_H_\n\n")
        for ln in lines:
            f.write(ln + "\n")
        f.write("\n#endif /* _CLI_KCONFIG_H_ */\n")

    print(f"Generated {header_path}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: config_to_header.py <.config> <output.h>")
        sys.exit(1)
    convert(sys.argv[1], sys.argv[2])
