#!/usr/bin/env python3
"""
Convert .config (key=value) to a C header and optionally a CMake file.
Strips the CONFIG_ prefix so existing source macros match.
Usage: python3 tools/config_to_header.py <.config> <output.h> [<output.cmake>]
"""
import re
import sys
import os


def convert(dotconfig_path: str, header_path: str, cmake_path: str = None):
    if not os.path.exists(dotconfig_path):
        print(f"Error: {dotconfig_path} not found.")
        sys.exit(1)

    header_lines = []
    cmake_vars = []

    with open(dotconfig_path, "r", encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            # format: # CONFIG_XXX is not set
            if line.startswith("#") and "is not set" in line:
                m = re.match(r"#\s*CONFIG_(\w+)\s+is not set", line)
                if m:
                    name = m.group(1)
                    header_lines.append(f"/* #undef {name} */")
                    cmake_vars.append((name, "n"))
                continue

            # format: CONFIG_XXX=value
            m = re.match(r"CONFIG_(\w+)=(.+)", line)
            if not m:
                continue
            name, val = m.group(1), m.group(2)
            cmake_vars.append((name, val))

            if val == "y":
                header_lines.append(f"#define {name} 1")
            elif val == "n":
                header_lines.append(f"/* #undef {name} */")
            else:
                # int, hex, string
                header_lines.append(f"#define {name} {val}")

    os.makedirs(os.path.dirname(header_path), exist_ok=True)

    with open(header_path, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by config_to_header.py, DO NOT EDIT */\n")
        f.write("#ifndef _CLI_KCONFIG_H_\n")
        f.write("#define _CLI_KCONFIG_H_\n\n")
        for ln in header_lines:
            f.write(ln + "\n")
        f.write("\n#endif /* _CLI_KCONFIG_H_ */\n")

    print(f"Generated {header_path}")

    if cmake_path:
        with open(cmake_path, "w", encoding="utf-8") as f:
            f.write("# Auto-generated by config_to_header.py, DO NOT EDIT\n")
            for name, val in cmake_vars:
                if val == "y":
                    f.write(f"set(CONFIG_{name} ON)\n")
                elif val == "n":
                    f.write(f"set(CONFIG_{name} OFF)\n")
                else:
                    f.write(f"set(CONFIG_{name} {val})\n")
        print(f"Generated {cmake_path}")


if __name__ == "__main__":
    if len(sys.argv) < 3 or len(sys.argv) > 4:
        print("Usage: config_to_header.py <.config> <output.h> [<output.cmake>]")
        sys.exit(1)
    convert(sys.argv[1], sys.argv[2], sys.argv[3] if len(sys.argv) == 4 else None)
