macro(lincli_build_object)
	get_filename_component(PRO_NAME ${CMAKE_CURRENT_SOURCE_DIR} NAME)
	project(${PRO_NAME})
	set(SOURCES "")
	foreach(dir ${SUBDIRS})
		file(GLOB_RECURSE TMP "${dir}/*.c")
		list(APPEND SOURCES ${TMP})
	endforeach()
	add_library(${PRO_NAME} OBJECT ${SOURCES})
	target_include_directories(${PRO_NAME} PUBLIC ${INCLUDE_DIRS})
endmacro()

macro(lincli_build_executable)
	get_filename_component(PRO_NAME ${CMAKE_CURRENT_SOURCE_DIR} NAME)
	project(${PRO_NAME})
	set(SOURCES "")
	foreach(dir ${SUBDIRS})
		file(GLOB_RECURSE TMP "${dir}/*.c")
		list(APPEND SOURCES ${TMP})
	endforeach()
	if(DEFINED EXTRA_SOURCES)
		list(APPEND SOURCES ${EXTRA_SOURCES})
	endif()
	add_executable(${PRO_NAME} ${SOURCES})
	target_include_directories(${PRO_NAME} PUBLIC ${INCLUDE_DIRS})
endmacro()
